### ISSUE TITLE
feature missing 

### ISSUE THREAD

**Issue by FidaKhoury** [Fullstack-Alfanar/team-work1#11]
hey, 
I was doing a test in the sing in page I noticed (in line 22) that it checks if the user exist in the local storage  the dashborad page opens,
but if not registered nothing happens .
So I dont know if you were planning to do it, but that is very important  for users to know .
thank you

**Comment by yosef406** [comment]
yes it should display an error message, 
i will add the flag now

**Comment by yosef406** [comment]
fixed
