### ISSUE TITLE
signin page email validation 

### ISSUE THREAD

**Issue by FidaKhoury** [Fullstack-Alfanar/team-work1#13]
hey, 
After a test I did on the email validation noticed that this "あいうえお@example.com" email address only the web gave an alert that it is not right, but as Elias told us we can not count on the web for check validation because if i change now the type to text it will fail.
please can you check also English letter .
thank you.

**Comment by yosef406** [comment]
i will update the `validateEmail()` function to check for that

**Comment by yosef406** [comment]
fixed it

**Comment by HosenNaser** [comment]
good work
