### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by HosenNaser** [Fullstack-Alfanar/team-work1#14]
In sign in page line 15 the href may cause a problems 
the # should be removed and switch it to your /main page or the URL of this page

**Comment by Amal031** [comment]
Hey Hossen,
Yes ! I  also agree with you.
But still,  its not the last version, because  we should apply  reroute later and **it can be a href.** or maybe we'll link by different way.

Regards
Amal

**Comment by yosef406** [comment]
done

**Comment by FidaKhoury** [comment]
well done
