### ISSUE TITLE
style recommendation

### ISSUE THREAD

**Issue by HosenNaser** [Fullstack-Alfanar/team-work1#16]
I know the style still not completed but, 
my recommendation is:
1. split the main container to more divs as you like .
2. set min-width to the buttons and inputs for web screens .
3. remove the width of the buttons and set the width of the btnDiv class to any percent you want.
4. set min/max-width to the "form" and "signInAria" class.

**Comment by Amal031** [comment]
hey Hossen,

Really thanks for your recommendations, some of which I've  fixed accordingly ..I found out that I used  flex Property mistakenly  in wrong lines . 

Regards,
Amal

**Comment by FidaKhoury** [comment]
thank you
