### ISSUE TITLE
Forget Password page 

### ISSUE THREAD

**Issue by FidaKhoury** [Fullstack-Alfanar/team-work1#22]
hello,
usually whenever you go to the forget password page it means you should check if the user exist better then checking if the email address is valid. After all we don't care if the email is valid here, only if exist . 
Thank you

**Comment by Amal031** [comment]
I checked  it again, you're right. I have  to do the same test to check in localstorage/ cookies if the user is already registered or not. working on it

thanks
Amal

**Comment by yosef406** [comment]
we did it as if the page has to check in a server (we don't have a server), the site should not give an indication if the email is a correct email or not,
normally the server sends an email to the email address entered.

**Comment by yosef406** [comment]
shame shame shame

**Comment by yosef406** [comment]
I DID IT WITH A CHECK IF THE EMAIL IS VALID, and the a message displays if the operation was successful.

**Comment by FidaKhoury** [comment]
WELLL DONE 👍
