### ISSUE TITLE
fix loading screen

### ISSUE THREAD

**Issue by HosenNaser** [Fullstack-Alfanar/team-work1#23]
https://github.com/Fullstack-Alfanar/team-work1/blob/0ada2b706d56eb646789a5fb073d3979303b89bc/index.html#L68

1. h6 should not be inside the svg tags .
2. nice loading screen but it's still loading for me 😂... connect JS and jQuery to the file .
3. In index.js file change the onload to Ready .

**Comment by yosef406** [comment]
this issue has been fixed

**Comment by yosef406** [comment]
this screen was fixed

**Comment by FidaKhoury** [comment]
GOOD JOB 👍
