### ISSUE TITLE
No documentation (תיעוד)

### ISSUE THREAD

**Issue by FidaKhoury** [Fullstack-Alfanar/team-work1#5]
Hello,
Most of your files has not a single line of explanation and it is very hard to understand which function / style / code represent what .
Specially  that you pushed a big chuck of code at once if you asked for our review a bit by bit it will be easier for you guys and us .

**Comment by Amal031** [comment]
Hello Fidaa, 
about your first  question , ya exactly as u've been suggested . . Personally, I had solve The  "Password validition" task  by hiding some elements in Javascrtipt .

About Your second suggestion,  I see you're right I rewrote accordingly :)..you can check it

Regards,
Amal

**Comment by FidaKhoury** [comment]
which first question are you referring to maybe you meant the other issue I opened, if you can answer each issue by it self.
And yes I noticed you added some documentation 👍 .
thank you.
