### ISSUE TITLE
sign up page

### ISSUE THREAD

**Issue by FidaKhoury** [Fullstack-Alfanar/team-work1#7]
hello,
in line 31 (sign up page) why the username's input of type email ? 
also line 52 why the "Already Have An Account? Sign In !" is a paragraph isn't supposed to be link/button ? 
thank you .

**Comment by Amal031** [comment]
Hey Fidaa,
Yes You're right , I changed the type of input to text.

and again about the second question.. I didn't write this mistakenly, because I  can link it to another page in Javascript by clicking on paragraph element by  matching the right Id and function.

Thanks,
Amal
